#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
//#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
//#pragma config(Motor,  mtr_S1_C1_1,     LeftDriveMotor, tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C1_2,     RightDriveMotor, tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C2_2,     Shooter,       tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C3_1,     BlockCollector, tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//#pragma config(Servo,  srvo_S1_C4_1,    Left,                 tServoStandard)
//#pragma config(Servo,  srvo_S1_C4_2,    Right,                tServoStandard)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Motors.h"
#include "Servos.h"

bool ServosDown = false;
bool Constant = 1.5;
long ArmPosition = 0;

void MoveLeft(int Power)
{
	Motors_SetSpeed(S1, 1, 1, Power);
	//motor[LeftDriveMotor] = Power;
	nxtDisplayString(1, "LeftPower: %i", Power);
	writeDebugStreamLine("Left %i", Power);
}

void RaiseServos()
{
	ServosDown = false;
}

void LowerServos()
{
	ServosDown = true;
}

void UpdateServos()
{
	if(ServosDown)
	{
		nxtDisplayString(4, "Down");
		Servos_SetPosition(S1, 4, 1, 0);
	}
	else
	{
		nxtDisplayString(4, "Up");
		Servos_SetPosition(S1, 4, 1, 120);
	}
}

void MoveRight(int Power)
{
	Motors_SetSpeed(S1, 1, 2, -Power);
	nxtDisplayString(2, "RightPower: %i", -Power);
	writeDebugStreamLine("Right %i", -Power);
}

void PickupBlocks(int Power)
{
	Motors_SetSpeed(S1, 3, 1, Power);
	nxtDisplayString(3, "PickupPower: %i", Power);

}

void MoveArm(int Power)
{
	Motors_SetSpeed(S1, 2, 1, -Power);
	nxtDisplayString(4, "ArmPower: %i", Power);
}

task main()
{
	//move the servos in the wait for start
	Servos_SetPosition(S1, 4, 2, 100);

	waitForStart();
	//stop the debugger from printing
	bDisplayDiagnostics = false;

	while(true)
	{
		//set the servo to the right position every cycle
		Servos_SetPosition(S1, 4, 2, 250);

		//update the servos
		UpdateServos();

		//sleep so that it can draw
		sleep(50);

		//erases display
		eraseDisplay();

		//updates each loop
		getJoystickSettings(joystick);

		//moves left side
		if(abs(joystick.joy1_y1) > 10)
		{
			MoveLeft(joystick.joy1_y1 / 1.26 * Constant);
		}
		else
		{
			MoveLeft(0);
		}

		//moves right side
		if(abs(joystick.joy1_y2) > 10)
		{
			MoveRight((joystick.joy1_y2 / 1.26 * Constant));
		}
		else
		{
			MoveRight(0);
		}

		//moves block picker-upper
		if(joystick.joy2_y1 > 10)
		{
			PickupBlocks(100);
		}
		else if (joystick.joy2_y1 < -10)
		{
			PickupBlocks(-100);
		}
		else
		{
			PickupBlocks(0);
		}



		//moves arm
		if(joystick.joy2_y2 > 10)
		{
			ArmPosition = 0;
			MoveArm(50);
		}
		else if(joystick.joy2_y2 < -10)
		{
			ArmPosition = 0;
			MoveArm(-10);
		}
		else
		{
			writeDebugStreamLine("Else", 7);
			if(ArmPosition == 0)
			{
				ArmPosition = Motors_GetPosition(S1, 2, 1);
			}
			if(Motors_GetPosition(S1, 2, 1) > ArmPosition)
			{
				Motors_SetSpeed(S1, 2, 1, -5);
			}
			else
			{
				Motors_SetSpeed(S1, 2, 1, 5);
			}
		}

		//if the right trigger is pressed, raise the servos
		if(joy1Btn(7) == 1)
		{
			RaiseServos();
			nxtDisplayString(5, "Raise");
		}
		//if the left trigger is pressed, lower the servos
		else if(joy1Btn(8) == 1)
		{
			LowerServos();
			nxtDisplayString(5, "Lower");
		}



		//if the left trigger is pressed, start shooting
		if(joy2Btn(7) == 1 || joy2Btn(8) == 1)
		{
			nxtDisplayString(6, "Shoot");
			Motors_SetSpeed(S1, 2, 2, 100);
		}
		//if x is pressed make the shooter go backwards
		else if(joy2Btn(1) == 1)
		{
			nxtDisplayString(6, "Reverse Shoot");
			Motors_SetSpeed(S1, 2, 2, -50);
		}
		//if neither trigger is pressed, stop shooting
		else
		{
			nxtDisplayString(6, "No Shoot");
			Motors_SetSpeed(S1, 2, 2, 0);
		}

		//lock the robot if both people press a
		if(joy1Btn(2) == 1 && joy2Btn(2) == 1)
		{
			Motors_SetPosition(S1, 1, 1, Motors_GetPosition(S1, 1, 1), 100);
			Motors_SetPosition(S1, 1, 2, Motors_GetPosition(S1, 1, 2), 100);
			break;
		}
	}
}
