#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     Gyro,           sensorI2CCustom)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Motors.h"
#include "Servos.h"
#include "Menu.c"
#include "Gyro.c"

bool WaitForStartBool = false;
int ArmPosition = 0;

void MoveLeft(int Power)
{
	motor[motorD] = Power;
	//motor[LeftDriveMotor] = Power;
	nxtDisplayString(1, "LeftPower: %i", Power);
}

void Shoot()
{
	motor[motorG] = 100;
	motor[motorH] = 100;
}

void StopShoot()
{
	motor[motorG] = 0;
	motor[motorH] = 0;
}

void RaiseServos()
{
	servo[servo1] = 120;
	// Servos_SetPosition(S1, 4, 1, 240);
}

void PickupBlocks(int Power)
{
	//Motors_SetSpeed(S1, 3, 1, Power);
	motor[motorH] = Power;
	nxtDisplayString(3, "PickupPower: %i", Power);
}

void MoveArm(int Power)
{
	//Motors_SetSpeed(S1, 2, 1, Power);
  motor[motorF] = -Power;
	nxtDisplayString(4, "ArmPower: %i", Power);
}

void LowerServos()
{
	servo[servo1] = 0;
	//Servos_SetPosition(S1, 4, 1, 70);
}

void MoveRight(int Power)
{
	//Motors_SetSpeed(S1, 1, 2, -Power);
  motor[motorE] = -Power;
	nxtDisplayString(2, "RightPower: %i", -Power);
}

void WaitForStartMenu()
{
	string t = "Wait for Start";
	string b = "Yes";
	string c = "No";
	int MenuReturn = Menu(t, b, c);

	if(MenuReturn == 0)
	{
		WaitForStartBool = true;
	}
	else if(MenuReturn == 1)
	{
		WaitForStartBool = false;
	}
}

void MainProgram()
{
	//raise the servos
	RaiseServos();

	int StartEncoder = nMotorEncoder[motorE];

	//go backward
	MoveLeft(-25);
	MoveRight(-30);

	sleep(500);

	MoveLeft(-5);
	MoveRight(-10);

	MoveArm(50);

	sleep(2000);

	servo[servo2] = 240;

	MoveArm(0);

	ArmPosition = nMotorEncoder[motorF];

	MoveLeft(-25);
	MoveRight(-30);

	while(nMotorEncoder[motorE] < StartEncoder + 1440 * 4.2)
	{
		writeDebugStreamLine("%i", nMotorEncoder[motorE]);
	}

	//stop
	MoveLeft(0);
	MoveRight(0);

	//FIRST TRY

	//grab the tube
	LowerServos();
	sleep(200);

	////SECOND TRY

	////turn right
	//MoveRight(-40);
	//MoveLeft(40);

	//sleep(600);

	//RaiseServos();
	//sleep(200);

	////move back
	//MoveRight(-40);
	//MoveLeft(-40);

	//sleep(400);

	////stop
	//MoveRight(0);
	//MoveLeft(0);

	////lower servos
	//LowerServos();
	//sleep(200);

	////THIRD TRY

	////turn right
	//MoveRight(-40);
	//MoveLeft(40);

	//sleep(600);

	////raise servos
	//RaiseServos();

	////move back
	//MoveRight(-40);
	//MoveLeft(-40);

	//sleep(400);

	////stop
	//MoveRight(0);
	//MoveLeft(0);

	////lower servos
	//LowerServos();
	//sleep(500);

	//TRY TO SCORE NOW
	//go Straight
	MoveLeft(40);
	MoveRight(40);

	sleep(500);

	MoveLeft(0);
	MoveRight(0);

	//go Straight
	MoveLeft(-80);
	MoveRight(-80);

	sleep(200);

	MoveRight(0);
	MoveLeft(0);

	PickupBlocks(100);

	Shoot();

	for(int i = 0; i < 500; i++)
	{
		sleep(10);

		if(nMotorEncoder[motorF] > ArmPosition)
		{
			MoveArm(5);
		}
		else
		{
			MoveArm(-5);
		}
	}

	StopShoot();
	PickupBlocks(0);

	//turn slightly right
	MoveRight(0);
	MoveLeft(60);
	sleep(1000);
	MoveRight(0);
	MoveLeft(0);

	int StartEndEncoder = nMotorEncoder[motorE];

	MoveLeft(30);
	MoveRight(30);

	while(nMotorEncoder[motorE] > StartEndEncoder - 1440 * 4.5)
	{
		writeDebugStreamLine("%i", nMotorEncoder[motorE]);
	}

	MoveLeft(0);
	MoveRight(0);
}

task main()
{
	Gyro_Start();
	//turn off joystick debug
	bDisplayDiagnostics = false;

	//lets the used pick the program
	WaitForStartMenu();

	eraseDisplay();

	//waits for start it bool is set
	if(WaitForStartBool)
	{
		waitForStart();
	}

	eraseDisplay();

	nxtDisplayString(3, "Running...");

	MoveLeft(-20);
	MoveRight(-20);

	sleep(1000);

	while(true)
	{
		eraseDisplay();
		nxtDisplayString(1, "%i", 20 - Gyro_Heading());
		MoveLeft(10 + Gyro_Heading());
		MoveRight(10);

		sleep(10);
	}

	MainProgram();


}
